exports.lineFacts = [
  ['A',
    'The initial segment of the IND (Independent Subway System) opened on September 10th, 1932, running from 207th St. to Chambers St.'
  ],
  ['B',
    'Service began on the newly-opened 6th Avenue lines on December 15th, 1940, heading southbound towards West 4th St-Washington Square.'
  ],
  ['C',
    'The line joins the A train on the 8th Avenue line—exactly five months from the A\'s first trip—on July 1st, 1933. It\'s initial route was from 205th St. to Jay St.'
  ],
  // ['D',
  //     ],
  // ['E',
  //     ],
  // ['F',
  //     ],
  // ['G',
  //     ],
  // ['H',
  //     ],
  // ['JFK Express',
  //     ],
  // ['J',
  //     ],
  // ['K',
  //     ],
  // ['L',
  //     ],
  // ['M',
  //     ],
  // ['N',
  //     ],
  // ['P',
  //     ],
  // ['Q',
  //     ],
  // ['R',
  //     ],
  // ['S',
  //     ],
  // ['R',
  //     ],
  // ['T',
  //     ],
  // ['U',
  //     ],
  // ['V',
  //     ],
  // ['W',
  //     ],
  // ['X',
  //     ],
  // ['Y',
  //     ],
  // ['Z',
  //     ],
  // ['1',
  //     ],
  // ['2',
  //     ],
  // ['3',
  //     ],
  // ['4',
  //     ],
  // ['5',
  //     ],
  // ['6',
  //     ],
  // ['7',
  //     ],
  // ['8',
  //     ],
  // ['9',
  //     ]
];
